# Generated by Django 5.0.6 on 2024-07-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_book_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="category",
            new_name="size",
        ),
    ]
