# Generated by Django 5.0.6 on 2024-07-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0003_rename_category_book_size"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="title",
            new_name="app",
        ),
    ]
