# Generated by Django 5.0.6 on 2024-07-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0004_rename_title_book_app"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="author",
            new_name="version",
        ),
    ]
