# Generated by Django 5.0.6 on 2024-07-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0005_rename_author_book_version"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="pdf",
            new_name="file",
        ),
    ]
