# Generated by Django 5.0.6 on 2024-07-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0006_rename_pdf_book_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="cover",
            new_name="logo",
        ),
    ]
