# Generated by Django 5.0.6 on 2024-07-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0007_rename_cover_book_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.FileField(upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="logo",
            field=models.ImageField(upload_to="logo/"),
        ),
    ]
