# Generated by Django 5.0.6 on 2024-07-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0008_alter_book_file_alter_book_logo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Book",
            new_name="Application",
        ),
    ]
